# Static analysis configuration for Dart & Flutter

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 🔹 Require doc comments for all public classes, methods & fields
    public_member_api_docs: true

    # 🔹 Some extra best-practice rules
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    unnecessary_this: true
    sort_constructors_first: true
    use_super_parameters: true
