name: flutter_easy_searchable_dropdown
description: A customizable, lightweight, and easy-to-use searchable dropdown widget for Flutter.
version: 0.1.9

homepage: https://github.com/Baralpartha/flutter_easy_searchable_dropdown
repository: https://github.com/Baralpartha/flutter_easy_searchable_dropdown
issue_tracker: https://github.com/Baralpartha/flutter_easy_searchable_dropdown/issues
documentation: https://github.com/Baralpartha/flutter_easy_searchable_dropdown#readme

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
